require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JewelriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Jewelry. As you add validations to Jewelry, be sure to
  # adjust the attributes here as well.
  let!(:collection) { create :collection }
  let(:valid_attributes) { attributes_for :jewelry, collection_id: collection.id }

  let(:invalid_attributes) { skip("Add a hash of attributes invalid for your model") }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JewelriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  login_admin

  describe "GET #index" do
    it "assigns all jewelries as @jewelries" do
      jewelry = Jewelry.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:jewelries)).to eq([jewelry])
    end
  end

  describe "GET #show" do
    it "assigns the requested jewelry as @jewelry" do
      jewelry = Jewelry.create! valid_attributes
      get :show, params: {id: jewelry.to_param}, session: valid_session
      expect(assigns(:jewelry)).to eq(jewelry)
    end
  end

  describe "GET #new" do
    it "assigns a new jewelry as @jewelry" do
      get :new, params: {}, session: valid_session
      expect(assigns(:jewelry)).to be_a_new(Jewelry)
    end
  end

  describe "GET #edit" do
    it "assigns the requested jewelry as @jewelry" do
      jewelry = Jewelry.create! valid_attributes
      get :edit, params: {id: jewelry.to_param}, session: valid_session
      expect(assigns(:jewelry)).to eq(jewelry)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Jewelry" do
        expect {
          post :create, params: {jewelry: valid_attributes}, session: valid_session
        }.to change(Jewelry, :count).by(1)
      end

      it "assigns a newly created jewelry as @jewelry" do
        post :create, params: {jewelry: valid_attributes}, session: valid_session
        expect(assigns(:jewelry)).to be_a(Jewelry)
        expect(assigns(:jewelry)).to be_persisted
      end

      it "redirects to the created jewelry" do
        post :create, params: {jewelry: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Jewelry.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved jewelry as @jewelry" do
        post :create, params: {jewelry: invalid_attributes}, session: valid_session
        expect(assigns(:jewelry)).to be_a_new(Jewelry)
      end

      it "re-renders the 'new' template" do
        post :create, params: {jewelry: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jewelry" do
        jewelry = Jewelry.create! valid_attributes
        put :update, params: {id: jewelry.to_param, jewelry: new_attributes}, session: valid_session
        jewelry.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested jewelry as @jewelry" do
        jewelry = Jewelry.create! valid_attributes
        put :update, params: {id: jewelry.to_param, jewelry: valid_attributes}, session: valid_session
        expect(assigns(:jewelry)).to eq(jewelry)
      end

      it "redirects to the jewelry" do
        jewelry = Jewelry.create! valid_attributes
        put :update, params: {id: jewelry.to_param, jewelry: valid_attributes}, session: valid_session
        expect(response).to redirect_to(jewelry)
      end
    end

    context "with invalid params" do
      it "assigns the jewelry as @jewelry" do
        jewelry = Jewelry.create! valid_attributes
        put :update, params: {id: jewelry.to_param, jewelry: invalid_attributes}, session: valid_session
        expect(assigns(:jewelry)).to eq(jewelry)
      end

      it "re-renders the 'edit' template" do
        jewelry = Jewelry.create! valid_attributes
        put :update, params: {id: jewelry.to_param, jewelry: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested jewelry" do
      jewelry = Jewelry.create! valid_attributes
      expect {
        delete :destroy, params: {id: jewelry.to_param}, session: valid_session
      }.to change(Jewelry, :count).by(-1)
    end

    it "redirects to the jewelries list" do
      jewelry = Jewelry.create! valid_attributes
      delete :destroy, params: {id: jewelry.to_param}, session: valid_session
      expect(response).to redirect_to(jewelries_url)
    end
  end

end
